name: Scrape

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Scrape ESPN
        uses: johnlindquist/kit-action@main
        with:
          script: scrape espn.com h2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
