name: Scrape

on:
  schedule:
    - cron: "* */6 * * *" # Every 6 hours
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Scrape ESPN
        uses: johnlindquist/kit-action@main
        with:
          script: scrape-espn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
